<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Информация о сайте</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<main class="container">
    <h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>
    <table class="table" data-test="url">
        <tr>
            <th>ID</th>
            <td><?= $url['id'] ?></td>
        </tr>
        <tr>
            <th>Имя</th>
            <td><?= htmlspecialchars($url['name']) ?></td>
        </tr>
        <tr>
            <th>Дата создания</th>
            <td><?= $url['created_at'] ?></td>
        </tr>
    </table>
</main>
</body>
</html>
