<main class="container">
    <h1>Сайты</h1>

    <?php if (!empty($flash['success'])): ?>
        <?php foreach ($flash['success'] as $msg): ?>
            <div class="alert alert-success"><?= htmlspecialchars($msg) ?></div>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if (!empty($flash['error'])): ?>
        <?php foreach ($flash['error'] as $msg): ?>
            <div class="alert alert-danger"><?= htmlspecialchars($msg) ?></div>
        <?php endforeach; ?>
    <?php endif; ?>

    <table class="table" data-test="urls">
        <thead>
        <tr>
            <th>ID</th>
            <th>Имя</th>
            <th>Дата создания</th>
            <th>Дата последней проверки</th>
            <th>Код ответа</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($urls as $url): ?>
            <tr>
                <td><?= $url['id'] ?></td>
                <td>
                    <a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a>
                </td>
                <td><?= $url['created_at'] ?></td>
                <td><?= $url['last_check'] ?? '' ?></td>
                <td><?= $url['last_status_code'] ?? '' ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</main>
